### ISSUE TITLE
How to poll asyncio from client?

### ISSUE THREAD

**Issue by icarito** [manatlan/redys#1]
I'm just beginning with asyncio and I think this library could help me but I need events. How should I poll `get_event` or is there a way for a client to be notified?

Thanks for your great libraries!

**Comment by manatlan** [comment]
In the simplest way, just poll, like this :

```python
while ws.client_state == WebSocketState.CONNECTED:
    message = await recver.get_event( EVENT )
    if message:
         await ws.send_text( message )
    await asyncio.sleep(0.001)
```
(Don't know if asyncio.sleep is really needed, but it can't be bad)
